SELECT ID, CASE
    WHEN E.P <= 0.25 THEN 'LOW'
    WHEN E.P <= 0.5 THEN 'MEDIUM'
    WHEN E.P <= 0.75 THEN 'HIGH'
    ELSE 'CRITICAL'
    END AS COLONY_NAME
    FROM (SELECT ID,
         PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS P
          FROM ECOLI_DATA) AS E
ORDER BY E.ID
