WITH REVIEWER_CNT AS (
SELECT MEMBER_ID, COUNT(*) as CNT
  FROM REST_REVIEW
 GROUP BY MEMBER_ID
),
MAX_REVIEWERS AS (
SELECT MEMBER_ID
  FROM REVIEWER_CNT
 WHERE CNT = (SELECT MAX(CNT) FROM REVIEWER_CNT)
)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d')
  FROM MEMBER_PROFILE M
  JOIN REST_REVIEW R
    ON M.MEMBER_ID = R.MEMBER_ID
 WHERE M.MEMBER_ID IN (SELECT * FROM MAX_REVIEWERS)
 ORDER BY REVIEW_DATE, REVIEW_TEXT;